

############################################################################
##                            Jenkins slave                              ### 
############################################################################

- name: copy script which will allow slave to join jenkins master automatically
  copy: 
    src: "{{ item }}"
    owner: ec2-user
    group: ec2-user
    mode: 0600
    dest: "/tmp/"
  with_items:
   - join-master.sh
   - job.xml